name: Install Languages CLI
description: Downloads the Languages CLI from a known release or installs using Cargo
inputs:
  branch:
    # This input is currently the only way we can modify which branch to install the CLI tooling from. Ideally we
    # would be able to use [`job_workflow_sha`](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context)
    # and always install from the same branch as the workflow but, due to a [bug](https://github.com/actions/runner/issues/2417)
    # in the GitHub Action runner, the value is never populated :(
    required: false
    description: The branch to install the CLI from (only used when `download_url` is not provided)
    default: main
  download_url:
    required: false
    description: The url to download the CLI binary from
    default: "https://github.com/heroku/languages-github-actions/releases/download/v1.1.0/actions.tar.gz"
  update_rust_toolchain:
    required: false
    description: Should we run `rustup update` as part of this composite action?
    default: "true"
runs:
  using: composite
  steps:
    - name: Update Rust toolchain
      shell: bash
      if: inputs.update_rust_toolchain == 'true' && inputs.download_url == ''
      run: rustup update
    - name: Build actions binary
      shell: bash
      if: inputs.download_url == ''
      run: cargo install --locked --git https://github.com/heroku/languages-github-actions.git --branch ${{ inputs.branch }}
    - name: Download actions binary
      shell: bash
      if: inputs.download_url != ''
      run: |
        mkdir -p ${{ runner.tool_cache }}/languages-github-actions
        curl ${{ inputs.download_url }} --output ${{ runner.temp }}/actions.tar.gz -L --fail --retry 5 --retry-all-errors --connect-timeout 10 --max-time 60
        tar -zxvf ${{ runner.temp }}/actions.tar.gz -C ${{ runner.tool_cache }}/languages-github-actions
        echo "${{ runner.tool_cache }}/languages-github-actions" >> $GITHUB_PATH
